### ISSUE TITLE
Want a logo?

### ISSUE THREAD

**Issue by DingosGotMyBaby** [tempestpark/NiceWeather#1]

**Comment by Gr8fulTed** [comment]
All issues have been addressed, in this section.

**Comment by Arvoreniad** [comment]
Watcha think?

![itunesartwork 2x](https://cloud.githubusercontent.com/assets/5327917/3903924/6205b620-22d2-11e4-9ab3-1648db953f2a.png)

**Comment by Gr8fulTed** [comment]
It's so good, that I'm gonna have to fire you and rehire you. Thanks Alex
Although.... I'd rather have had the two of you fight for it.......

**Comment by Arvoreniad** [comment]
Why do I have to be fired and rehired?

**Comment by Gr8fulTed** [comment]
Because it is that great thet you deserve to be fired and rehired.

**Comment by Arvoreniad** [comment]
At a higher salary?

**Comment by Gr8fulTed** [comment]
Fine you get paid cat gifs this time.

**Comment by Arvoreniad** [comment]
Well you'll have to see my work on the app design first

**Comment by Gr8fulTed** [comment]
What have you got, fine sir?

**Comment by Arvoreniad** [comment]
Nothing yet

**Comment by Arvoreniad** [comment]
I'll work on it tomorrow

**Comment by DingosGotMyBaby** [comment]
Did I just get kicked off the team?

**Comment by Arvoreniad** [comment]
Contributions are the only prerequisite for being on the team

**Comment by Gr8fulTed** [comment]
Okay Thanks Alex

**Comment by Gr8fulTed** [comment]
OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH SNAP 

Rule #1 Lach015 Rule #1

**Comment by DingosGotMyBaby** [comment]
![kavi lagos_edited-1](https://cloud.githubusercontent.com/assets/7553117/3928535/ef5c00a8-240b-11e4-83a1-0d3e0f8a314c.jpg)
What about this?
