### ISSUE TITLE
Well someone's been busy

### ISSUE THREAD

**Issue by Gr8fulTed** [tempestpark/NiceWeather#2]
Sorry, I have been in bed sick all this time.
Dude you have done a ton of work.
Now that I'm better, I better start pulling my weight.

**Comment by Arvoreniad** [comment]
No worries man.

So I'm forging ahead pretty nicely with the app and this Cordova business. (http://cordova.io) If you've got some time to work, it'd be great if you could get started on the Sinatra backend. 

Look at the docs on http://sinatrarb.com to get started, but feel free to open an issue if you're stuck. Put your stuff in the /api folder. You don't need any really high-level Ruby knowledge, so if you've looked through LRTHW, you should be good to go.
